syntax = "proto3";

package media;

import "google/protobuf/empty.proto";

option go_package = "media.v1;mediav1";

service Media {
    rpc GetUploadURL (GetURLRequest) returns (GetURLResponse);
    rpc DeleteFile (DeleteFileRequest) returns (google.protobuf.Empty);
}

message GetURLRequest {
  string filename = 1;
  bool visible = 2;
}

message GetURLResponse {
    string url = 1;
    string filekey = 2;
    string type = 3;
}

message DeleteFileRequest {
    string key = 1;
    bool visible = 2;
}
