syntax = "proto3";

package backend;

import "google/protobuf/empty.proto";

option go_package = "backend.v1;backendv1";

service Backend {
    rpc CompleteFileProcessing (CompleteFileProcessingRequest) returns (google.protobuf.Empty);
}

enum OperationStatus {
    OPERATION_APPROVED = 0;
    OPERATION_FAILED = 1;
}

message CompleteFileProcessingRequest {
    string file_id = 1;
    string new_key = 2;
    OperationStatus status = 3;
    optional string error_message = 4;
    int64 size_bytes = 5;
}